# Aspect Definitions
# This file contains aspect type definitions and their properties

# Aspect Definitions
aspects:

  
  datasetProperties:
    type: versioned
    properties:
      - description
      - customProperties
      - tags
      - externalUrl
    required: ["description"]
    entity_creation:
      entity_type: "Dataset"
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]
  
  schemaMetadata:
    type: versioned
    properties:
      - schemaName
      - platform
      - version
      - fields
      - primaryKeys
      - foreignKeys
    required: ["schemaName", "platform", "fields"]
    entity_creation:
      entity_type: "Dataset"
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]
  
  ownership:
    type: versioned
    properties:
      - owners
      - groupOwners
      - lastModified
    required: ["owners"]
    # Ownership can be attached to multiple entity types
    # Entity creation will be determined by the context where it's used
    entity_creation:
      entity_type: "Dataset"  # Default to Dataset, but can be overridden
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]
  
  globalTags:
    type: versioned
    properties:
      - tags
    required: ["tags"]
    # Global tags can be attached to multiple entity types
    # Entity creation will be determined by the context where it's used
    entity_creation:
      entity_type: "Dataset"  # Default to Dataset, but can be overridden
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]
  
  datasetProfile:
    type: timeseries
    properties:
      - rowCount
      - columnCount
      - sizeInBytes
      - lastModified
      - partitionCount
    required: ["rowCount", "columnCount"]
    entity_creation:
      entity_type: "Dataset"
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]

  corpUserInfo:
    type: versioned
    properties:
      - active
      - displayName
      - email
      - title
      - managerUrn
      - departmentId
      - departmentName
      - firstName
      - lastName
      - fullName
      - countryCode
    required: ["active", "displayName", "email"]
    entity_creation:
      entity_type: "CorpUser"
      urn_generator: "corpUser"
      required_params: ["username"]
      optional_params: []

  corpGroupInfo:
    type: versioned
    properties:
      - displayName
      - description
      - email
      - admins
      - members
      - groups
    required: ["displayName"]
    entity_creation:
      entity_type: "CorpGroup"
      urn_generator: "corpGroup"
      required_params: ["name"]
      optional_params: []

  columnProperties:
    type: versioned
    properties:
      - description
      - dataType
      - nullable
      - defaultValue
      - customProperties
    required: ["dataType"]
    entity_creation:
      entity_type: "Column"
      urn_generator: "column"
      required_params: ["dataset_urn", "field_path"]
      optional_params: []

  columnTransformation:
    type: versioned
    properties:
      - inputColumns
      - transformType
      - transformScript
      - sourceDataset
    required: ["inputColumns", "transformType"]
    entity_creation:
      entity_type: "Column"
      urn_generator: "column"
      required_params: ["dataset_urn", "field_path"]
      optional_params: []

  datasetTransformation:
    type: versioned
    properties:
      - sourceDataset
      - targetDataset
      - transformationType
      - description
    required: ["sourceDataset", "targetDataset"]
    entity_creation:
      entity_type: "Dataset"
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]

  dataQuality:
    type: versioned
    properties:
      - qualityScore
      - qualityMetrics
      - lastValidated
      - validationRules
      - dataQualityIssues
      - qualityChecks
    required: ["qualityScore", "lastValidated"]
    entity_creation:
      entity_type: "Dataset"
      urn_generator: "dataset"
      required_params: ["platform", "name"]
      optional_params: ["env"]
 